### ISSUE TITLE
Add brief description of Digital Development of the RTC site

### ISSUE THREAD

**Issue by ps2270** [cu-mkp/research-teaching-companion#125]
@tcatapano 
Please compose a very brief description of the digital development of the RTC site, which will be entered under "Digital Development of the Research and Teaching Companion" on the About M&K page: https://cu-mkp.github.io/research-teaching-companion/about/

We'll just enter it directly onto the Index page for the About M&K page: https://github.com/cu-mkp/research-teaching-companion/blob/main/content/about.md

**Comment by ps2270** [comment]
@tcatapano @njr2128 I updated this on the "Introduction" webpage, but it needs correcting/revising.

**Comment by ps2270** [comment]
@tcatapano please read, revise, sign off on the following description of Digital Development, then close this issue:

Webpage content and navigation for the [Making and Knowing Project](https://makingandknowing.org/)’s Research and Teaching Companion is built on the [Hugo](https://gohugo.io/) framework. Find the Companion on GitHub: https://cu-mkp.github.io/research-teaching-companion/.

**Comment by njr2128** [comment]
You must use html syntax instead of markdown:
`<img src="/images/sp22_azurite-session.jpg" alt="Making and Knowing Lab azurite session" width="640" height="360"/>`
You can play around with the width/height as you'd like. 
https://www.w3schools.com/tags/tag_img.asp -- look at the other attributes available for the image tag - might be able to use the alignment attribute to center?

**Comment by ps2270** [comment]
looks great. closing now.
