### ISSUE TITLE
Rendering of tables in RTC

### ISSUE THREAD

**Issue by ps2270** [cu-mkp/research-teaching-companion#57]
When material is migrated from the Sandbox, the table grids are erased and all data is merged together. Can we fix this easily?

**Comment by njr2128** [comment]
Can you show us an example? link and screenshot?

**Comment by ps2270** [comment]
See ghoneima essay or the credits on about page

**Comment by njr2128** [comment]
SOLUTION:
Instead of using markdown table syntax, use html with the following attributes:
`<table>` --> `<table border=1>`
`<td>` --> `<td valign=top>`

For example:
 ```
<table border=1>
<thead>
<tr>
<th>2014 Fall: Moldmaking and Metalworking</th>
<th>2015 Spring: Moldmaking and Metalworking</th>
</tr>
</thead>
<tbody>
<tr>
<td valign=top>Emily Boyd <br><br> Raymond Carlson <br><br> Emogene Cataldo <br><br> Jordan Katz <br><br> Rozemarijn Landsman <br><br> Michelle Lee <br><br> Diana Mellon <br><br> Jef Palframan <br><br> Jonah Rowen <br><br> Julianna Visco <br><br> Yijun Wang</td>
<td valign=top>Giulia Chiostrini <br><br> Celia Durkin <br><br> Shiye Fu <br><br> Sofia Gans <br><br> Caroline Marris <br><br> Jef Palframan <br><br> Gunthild Peters <br><br> Stephanie Pope <br><br> Zhiqi Zhang</td>
</tr>
</tbody>
</table>
```

**Comment by njr2128** [comment]
See also  https://developer.mozilla.org/en-US/docs/Web/HTML/Element/td and https://developer.mozilla.org/en-US/docs/Web/HTML/Element/table
-- note that these are ways to edit the element through attributes instead of changing the CSS. As noted in the links, many of these attributes are depreciated and should not be used.
Also helpful: https://www.dofactory.com/html/table/style
